### ISSUE TITLE
Nerd Icons?

### ISSUE THREAD

**Issue by summeremacs** [seagle0128/nerd-icons-ibuffer#2]
Hi!
I'm posting the picture here because I'm a little confused: Are these nerd-icons-ibuffer or all-the-icons? They look just like the all-the-icons stuff I used to have. I did all the instructional stuff including installing the fonts by downloading them and running the M-x command for installing nerd icons fonts as well. Please let me know if I'm missing something?

Thx!

<img width="301" alt="Nerd Icons" src="https://github.com/seagle0128/nerd-icons-ibuffer/assets/108068046/81d062d6-248a-44e7-9181-b8e1a11a1e1c">

**Comment by seagle0128** [comment]
They are nerd icons. See https://github.com/rainstormstudio/nerd-icons.el.
